import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { insertImport } from '@schematics/angular/utility/ast-utils';
import { InsertChange } from '@schematics/angular/utility/change';
import { getProject, readIntoSourceFile } from '../../utils/angular-utils';
import { findAppModulePath } from './add-module-import';
import ts = require('typescript');

interface AppModuleInfo {
  className: string;
  declarations: string[];
}

// The root component spec generated by `ng new --standalone=false` declares the
// component in the TestBed without importing its NgModule. The unit-test builder
// only compiles files reachable from the specs, so the component would be
// compiled without the scope of its NgModule (e.g. `<router-outlet>` unknown)
// and without the auth configuration added to the module by this schematic.
// Importing the app module in the TestBed instead of re-declaring its
// components fixes both.
export function addAppModuleToAppSpec(): Rule {
  return (host: Tree, context: SchematicContext) => {
    const [, project] = getProject(host);
    const appModulePath = findAppModulePath(host, project.sourceRoot);

    if (!appModulePath) {
      return host;
    }

    const appFolder = appModulePath.substring(0, appModulePath.lastIndexOf('/'));
    const specPath = [`${appFolder}/app.spec.ts`, `${appFolder}/app.component.spec.ts`].find((path) => host.exists(path));

    if (!specPath) {
      return host;
    }

    const appModule = getAppModuleInfo(readIntoSourceFile(host, appModulePath));
    const specFile = readIntoSourceFile(host, specPath);
    const testingModule = findTestingModuleDefinition(specFile);

    if (!appModule || !testingModule) {
      context.logger.info(`ℹ️ Could not update '${specPath}', please import '${appModule?.className ?? 'AppModule'}' in its TestBed.`);

      return host;
    }

    const importsArray = getArrayProperty(testingModule, 'imports');

    if (importsArray?.elements.some((element) => element.getText() === appModule.className)) {
      return host;
    }

    const recorder = host.beginUpdate(specPath);
    const moduleImportPath = `./${appModulePath.substring(appFolder.length + 1).replace(/\.ts$/, '')}`;
    const importChange = insertImport(specFile, specPath, appModule.className, moduleImportPath);

    if (importChange instanceof InsertChange) {
      recorder.insertLeft(importChange.pos, importChange.toAdd);
    }

    removeModuleDeclarations(recorder, specFile, testingModule, appModule.declarations);
    addToImports(recorder, specFile, testingModule, importsArray, appModule.className);

    host.commitUpdate(recorder);
    context.logger.info(`✅️ '${appModule.className}' is imported in the TestBed of '${specPath}'`);

    return host;
  };
}

function getAppModuleInfo(moduleFile: ts.SourceFile): AppModuleInfo | null {
  for (const statement of moduleFile.statements) {
    if (!ts.isClassDeclaration(statement) || !statement.name) {
      continue;
    }

    const ngModuleArgument = ts
      .getDecorators(statement)
      ?.map((decorator) => decorator.expression)
      .find(
        (expression): expression is ts.CallExpression =>
          ts.isCallExpression(expression) && expression.expression.getText() === 'NgModule'
      )?.arguments[0];

    if (ngModuleArgument && ts.isObjectLiteralExpression(ngModuleArgument)) {
      const declarations = getArrayProperty(ngModuleArgument, 'declarations');

      return {
        className: statement.name.text,
        declarations: declarations?.elements.map((element) => element.getText()) ?? [],
      };
    }
  }

  return null;
}

function findTestingModuleDefinition(specFile: ts.SourceFile): ts.ObjectLiteralExpression | null {
  let result: ts.ObjectLiteralExpression | null = null;

  const visit = (node: ts.Node): void => {
    if (
      !result &&
      ts.isCallExpression(node) &&
      ts.isPropertyAccessExpression(node.expression) &&
      node.expression.name.text === 'configureTestingModule' &&
      node.arguments[0] &&
      ts.isObjectLiteralExpression(node.arguments[0])
    ) {
      result = node.arguments[0];
    }

    ts.forEachChild(node, visit);
  };

  visit(specFile);

  return result;
}

function getArrayProperty(objectLiteral: ts.ObjectLiteralExpression, name: string): ts.ArrayLiteralExpression | null {
  const property = findProperty(objectLiteral, name);

  return property && ts.isArrayLiteralExpression(property.initializer) ? property.initializer : null;
}

function findProperty(objectLiteral: ts.ObjectLiteralExpression, name: string): ts.PropertyAssignment | null {
  const property = objectLiteral.properties.find(
    (property): property is ts.PropertyAssignment =>
      ts.isPropertyAssignment(property) && property.name.getText() === name
  );

  return property ?? null;
}

// A component can only be declared in one NgModule, so the components
// declared by the app module are removed from the TestBed declarations.
function removeModuleDeclarations(
  recorder: ReturnType<Tree['beginUpdate']>,
  specFile: ts.SourceFile,
  testingModule: ts.ObjectLiteralExpression,
  moduleDeclarations: string[]
): void {
  const declarationsProperty = findProperty(testingModule, 'declarations');

  if (!declarationsProperty || !ts.isArrayLiteralExpression(declarationsProperty.initializer)) {
    return;
  }

  const declarationsArray = declarationsProperty.initializer;
  const remaining = declarationsArray.elements.filter((element) => !moduleDeclarations.includes(element.getText()));

  if (remaining.length === declarationsArray.elements.length) {
    return;
  }

  if (remaining.length > 0) {
    recorder.remove(declarationsArray.getStart(), declarationsArray.getWidth());
    recorder.insertLeft(declarationsArray.getStart(), `[${remaining.map((element) => element.getText()).join(', ')}]`);

    return;
  }

  // Remove the whole property including its leading whitespace and trailing comma.
  const start = declarationsProperty.getFullStart();
  let end = declarationsProperty.getEnd();

  if (specFile.text[end] === ',') {
    end++;
  }

  recorder.remove(start, end - start);
}

function addToImports(
  recorder: ReturnType<Tree['beginUpdate']>,
  specFile: ts.SourceFile,
  testingModule: ts.ObjectLiteralExpression,
  importsArray: ts.ArrayLiteralExpression | null,
  className: string
): void {
  if (!importsArray) {
    const firstProperty = testingModule.properties[0];

    if (firstProperty) {
      recorder.insertLeft(firstProperty.getStart(), `imports: [${className}],\n${getIndentation(specFile, firstProperty)}`);
    } else {
      recorder.insertLeft(testingModule.getStart() + 1, ` imports: [${className}] `);
    }

    return;
  }

  const lastElement = importsArray.elements[importsArray.elements.length - 1];

  if (!lastElement) {
    recorder.insertLeft(importsArray.getStart() + 1, className);

    return;
  }

  const isMultiline =
    specFile.getLineAndCharacterOfPosition(importsArray.getStart()).line !==
    specFile.getLineAndCharacterOfPosition(lastElement.getStart()).line;
  const separator = isMultiline ? `,\n${getIndentation(specFile, lastElement)}` : ', ';

  recorder.insertRight(lastElement.getEnd(), `${separator}${className}`);
}

function getIndentation(specFile: ts.SourceFile, node: ts.Node): string {
  const { line } = specFile.getLineAndCharacterOfPosition(node.getStart());
  const lineStart = specFile.getPositionOfLineAndCharacter(line, 0);

  return specFile.text.substring(lineStart, node.getStart()).match(/^\s*/)?.[0] ?? '';
}
